version: '3.8'

services:
  web:
    build: .  # Replace with path to your project directory if different
    restart: always
    environment:
      - DB_HOST= 'mysql' 
      - DB_USER= 'root'  # Replace with your actual username
      - DB_PASSWORD= 'root'  # Replace with your actual password
      - DB_DATABASE= 'team_db'
      # Add other environment variables as needed
    ports:
      - 8080:8080  # Replace 3000 with your desired port for the web app
    depends_on:
      - mysql

  mysql:
    build: ./sql_server/  # Adjust path if your Dockerfile is elsewhere
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
