version: '3.8'

services:
  web:
    build: .  
    restart: always
    environment:
      - DB_HOST= 'mysql' 
      - DB_USER= 'root'  
      - DB_PASSWORD= 'root'  
      - DB_DATABASE= 'team_db'
    ports:
      - 8080:8080  
    volumes:
      - app_data:/app/data
    depends_on:
      - mysql

  mysql:
    build: ./sql_server/  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql-data:/var/lib/MySQL
volumes:
  mysql-data:
  app_data: